# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: efece9ba04013501ab849729a06d344bcefa9984e417448c221723c31e2dfdc261d1595f4a5c95a44dfc875ab3755f98e34248f0190bc263fb03ba97d71eda3c

test:
  secret_key_base: 92d756c5aa4d7b9b0919a1bcf095ddc0509ad3b02fc0a66f0c103a60da697d4a96514d8dc16df40caeed2aefb74e5213640b2383eb4c286362a154463a6f3e90

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
